"""Add response field into Logs table

Revision ID: 4254134a8f13
Revises: 
Create Date: 2024-03-24 17:11:47.608497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4254134a8f13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peer_1', sa.String(), nullable=False),
    sa.Column('peer_2', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peer_1', sa.String(), nullable=False),
    sa.Column('peer_2', sa.String(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite')
    op.drop_table('friend')
    # ### end Alembic commands ###
